Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -201,6 +201,12 @@ jobs:
       
           # Create a new keychain with restricted permissions
           security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
+          if [ $? -ne 0 ]; then
+              echo "Error creating keychain"
+              exit 1
+          fi
+          chmod 600 "$KEYCHAIN_PATH"
+          echo "Keychain created: $KEYCHAIN_NAME"
       
           # Set the keychain as the default keychain
           security default-keychain -s "$KEYCHAIN_PATH"
@@ -209,9 +215,6 @@ jobs:
           # Unlock the keychain
           security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
           echo "Attempted to unlock keychain: $KEYCHAIN_PATH"
-
-          chmod 777 "$KEYCHAIN_PATH"
-          echo "Keychain created: $KEYCHAIN_NAME"
       
           # Check if the keychain is unlocked
           UNLOCK_STATUS=$(security show-keychain-info "$KEYCHAIN_PATH" 2>&1 || echo "Keychain is locked")
