Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -194,7 +194,7 @@ jobs:
                 
       - name: Import certificate to keychain
         run: |
-          # Path to the keychain
+# Path to the keychain
           KEYCHAIN_NAME="build.keychain"
           KEYCHAIN_PASSWORD="private_pass"
           CERT_P12_PASSWORD="private_pass"
@@ -242,18 +242,45 @@ jobs:
           
           # Set key partition list for the keychain
           security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
+          if [ $? -ne 0 ]; then
+              echo "Error setting key partition list"
+              exit 1
+          fi
           echo "Key partition list set for keychain: $KEYCHAIN_PATH"
+          
+          # Debug: Verify the existence of the .p12 file and provisioning profile
+          if [ ! -f "distribution.p12" ]; then
+              echo "Error: distribution.p12 file not found"
+              exit 1
+          fi
+          if [ ! -f "provisioning_profile.mobileprovision" ]; then
+              echo "Error: provisioning_profile.mobileprovision file not found"
+              exit 1
+          fi
           
           # Import the .p12 file into the keychain
           security import distribution.p12 -k "$KEYCHAIN_PATH" -P "$CERT_P12_PASSWORD" -T /usr/bin/codesign
+          if [ $? -ne 0 ]; then
+              echo "Error importing certificate"
+              exit 1
+          fi
           echo "Certificate import attempt completed."
           
           # Import the provisioning profile into the keychain
           security import provisioning_profile.mobileprovision -k "$KEYCHAIN_PATH"
+          if [ $? -ne 0 ]; then
+              echo "Error importing provisioning profile"
+              exit 1
+          fi
           echo "Provisioning profile import attempt completed."
           
           # Validate that the certificate is present in the keychain
-          security find-certificate -a -c "Apple Distribution: KLQ SOLUCOES TECNOLOGICAS LTDA" -p
+          CERT_NAME="Apple Distribution: KLQ SOLUCOES TECNOLOGICAS LTDA"
+          CERTIFICATE=$(security find-certificate -a -c "$CERT_NAME" -p "$KEYCHAIN_PATH" 2>&1)
+          if [[ "$CERTIFICATE" == *"could not be found"* ]]; then
+              echo "Error: Certificate not found in keychain"
+              exit 1
+          fi
           echo "Certificate found and validated in keychain"
           
           # Print the keychain contents for debugging (optional)
